name: Actions
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    runs-on: ${{matrix.os}}
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      # Setup several versions of Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - run: ls -la
      - run: make lint