name: Actions
# on – определяет события, которые запускают воркфлоу
on: push

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8, 3.9]
        # several OS
        os: [ ubuntu-latest, macos-latest ]

      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - run: ls -la
      - run: make lint